#!/bin/bash

JSON commands new
JSON options new
export_module commands options

_require_sudo $*

sfproject=($(_is_sfs_project $PWD))
sfp_path="$PWD"
sfp_name=${sfproject[0]}
sfp_version=${sfproject[1]}
# ------ CODE ------

rm -fr "$PWD/$COMPILE_FOLDER"

sconsole -a "Clean successfuly"

