#!/bin/bash

JSON commands new
JSON options new

export_module commands options

if [[ ! $2 ]]; then
    sconsole -e "sfs create [NAME]. Param name Not found"
    exit 0
fi

name="$2"
echo "Creando proyecto SFS [ $name ]"
mkdir $name
cd $name

cat >"README.md" <<EOF
# sfs
EOF

mkdir "src"
cd "src"

mkdir "cmd"
mkdir "cmd/test/"

cat >"$name.sfs" <<EOF
VERSION=1.0.1
EOF

cat >"$name" <<EOF
#!/bin/bash

#[WARNING] Import sfs only in first page.
source "sfs"

JSON commands new
JSON commands put "test" "cmd/test/index"

JSON options new

JSON options put "-h" "_help"
JSON options put "--help" "_help"

JSON options put "-v" "_version"
JSON options put "--version" "_version_large"

_help() {
    JSON help_info new
    JSON help_info put "cmd/test/index" "Testing"

    JSON help_info put "_help" "Muestra la ayuda."
    JSON help_info put "_version" "Muestra la version de $NAME."
    JSON help_info put "_version_large" "Muestra la version detallada de $NAME."

    shelp commands options help_info ""
    exit 0
}
_version() {
    sconsole "\$VERSION"
    exit 0
}
_version_large() {
    sconsole "\$NAME version \$VERSION"
    sfs --version
    exit 0
}

export_module commands options

_help
EOF

chmod +x "$name"

cat >"cmd/test/index" <<EOF
#!/bin/bash

JSON commands new

JSON options new

JSON options put "-h" "_help"

_help() {
    JSON help_info new
    JSON help_info put "_help" "Muestra la ayuda."
    shelp commands options help_info "test"
    exit 0
}

export_module commands options

echo "TODO DEVELOP PAGE /src/cmd/test/index" 
# _help
EOF
