#!/bin/bash

JSON commands new
JSON options new
export_module commands options

_require_sudo $*

package=${PARAMS[1]}

include "cmd/repo/index"

if [ ! -z $package ]; then
    path_to_package=$(type -a $package)
    if [ ! -s "$path_to_package" ]; then
        repo_path=$(_repo_find $package)
        if [ -s $repo_path ]; then
            sconsole -e "El paquete no pertence a SFS, se cancelo el borrado!"
            exit 0
        fi
        rm -fr "${path_to_package[2]}"
        rm -fr "/opt/$package"
        sconsole -a "El paquete fue borrado con exito."
    fi
else
    sconsole -e "Debe ingresar el nombre del paquete"
fi

# rm -fr "$BIN_PATH/$sfp_name"
# rm -fr "$INSTALATION_PATH/$sfp_name"
# echo "$BIN_PATH/$sfp_name"
# echo "$INSTALATION_PATH/$sfp_name"

# sconsole -a "Uninstall succeded"
