#!/bin/bash

JSON commands new
JSON options new
export_module commands options

sfproject=($(_is_sfs_project $PWD))
sfp_path="$PWD"
sfp_name=${sfproject[0]}
sfp_version=${sfproject[1]}
# ------ CODE ------

rm -fr "$BIN_PATH/$sfp_name"
rm -fr "$INSTALATION_PATH/$sfp_name"
# echo "$BIN_PATH/$sfp_name"
# echo "$INSTALATION_PATH/$sfp_name"

sconsole -a "Unlink succeded"
