#!/bin/bash

_exist "name" $1

name=$1

arr=($(JSON $name spread))
for row in ${arr[@]}; do
    k="$(cut -d ':' -f 1 <<<"$row")"
    # v=$(echo $row | rev | grep -o '.*:' | rev | sed 's/^://')
    echo "$k"
done
