#!/bin/bash

str_data=${!1}

arrfinal=()
str_row=""

lvl_find=(1)
lvl=(0)
IFS='{' read -ra arr_llaves <<<"$str_data"
for key in ${arr_llaves[@]}; do
    lvl=$(($lvl + 1))
    if [[ ! $lvl -eq $lvl_find ]]; then
        str_row="$str_row{"
    fi

    IFS=',' read -ra arr_comas <<<"$key"
    for key2 in ${arr_comas[@]}; do
        line="${key2//[!\}]/}"
        cant_close="${#line}"

        IFS='}' read -ra arr_close <<<"$key2"
        for key3 in ${arr_close[@]}; do
            if [[ $lvl -eq $lvl_find ]]; then
                arrfinal=(${arrfinal[*]} $str_row)
                str_row=$key3
            else
                lastLetter="${str_row: -1}"
                list_allow_coma=("{")
                if [[ " ${list_allow_coma[*]} " =~ " ${lastLetter} " ]]; then
                    # whatever you want to do when array contains value
                    str_row="$str_row$key3"
                else
                    str_row="$str_row,$key3"

                fi
            fi
        done

        if [[ $cant_close -gt 0 ]]; then
            for ((c = 1; c <= $cant_close; c++)); do
                if [[ ! $lvl -eq $lvl_find ]]; then
                    str_row="$str_row}"
                fi
                lvl=$(($lvl - 1))
            done

        fi
    done
done
arrfinal=(${arrfinal[*]} $str_row)

echo "${arrfinal[*]}"
