#!/bin/bash

JSON commands new
JSON options new
JSON options put "-h" "_help"
JSON options put "-f{2}" "_file"

_help() {
    shelp commands options
}
_file() {
    # FILE1=$1
    # FILE2=$2
    sconsole "_file() $*"
}

export_module commands options

